### ISSUE TITLE
Backend exception and messed up records when moving records

### ISSUE THREAD

**Issue by h-e-l-l-o-w-o-r-l-d** [bihor/fp_masterquiz#32]
Hi,

I found a major bug. :) Tried to move records of a poll from one page to another and this messed up quite some things. Error in backend and corrupt records with UIDs of sorting-like values: 64,128, 256 and so on. See attached screenhots.

It seems to only happen when you try to move records from table tx_fpmasterquiz_domain_model_selected or tx_fpmasterquiz_domain_model_participant.

![fp_masterquiz_2](https://user-images.githubusercontent.com/51790093/151536003-1dbfdf56-befe-43d6-b1ee-4f9e73331bea.png)

![fp_masterquiz_1](https://user-images.githubusercontent.com/51790093/151536005-2f0d79b1-1dba-47df-aa4f-d6b57c431d14.png)

**Comment by bihor** [comment]
Yes, I can confirm this bug, but why do you think it has something with sorting in common?
It seem that TYPO3 wants to change the UID of a selected-entry.
The scissors is TYPO3 core feature but I found out that the error disapears when I delete the sorting-entry in the TCA file tx_fpmasterquiz_domain_model_selected.php.
It should be fixed in version 3.2.7

**Comment by h-e-l-l-o-w-o-r-l-d** [comment]
"Why do you think it has something with sorting in common?"

Look at the first 3 uids of my smaller screenshot. This happened with the records after the error.

**Comment by bihor** [comment]
There was a sorting entry in the TCA and it seems that sorting was used therefore for the UID after moving.
I removed that entry and than it works correct for me.
Have you tested the new version?

**Comment by h-e-l-l-o-w-o-r-l-d** [comment]
It works, thank you!
